### ISSUE TITLE
JSON-LD Frame for schemaorg:GeoShape

### ISSUE THREAD

**Issue by ashepherd** [earthcubearchitecture-project418/crawler#2]
With the GeoShape , this frame let's users define GeoJSON as the subjectOf the GeoShape and/or use the GeoShape properties like circle, polygon, line, box, and elevation.

https://json-ld.org/playground/#/gist/6e798a6c3e79ba8063e3d7f2b76c4ec5

**Comment by fils** [comment]
resolved by Adam's pull request
