### ISSUE TITLE
Mashing up appendonly.aof for tile38

### ISSUE THREAD

**Issue by ashepherd** [earthcubearchitecture-project418/crawler#7]
appendonly.aof does a warm boot for Redis. Mashing two of these files together should be completely fine especially if the keys don't collide. I've put the BCO-DMO aof file on geodex at /rot/bcodmo/

**Comment by fils** [comment]
I'm closing this here..  it's more an issue for the services or documentation repo's.  
Sounds like it is resolved so no need to re-open it elsewhere..  just need to know it and make sure it's part of P418 "memory".
